version: '3'
services:
  web:
    build: .
    container_name: 'brevet_webapp'
    ports:
      - 5000:5000
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    container_name: 'brevetdb'
    ports:
      - 27017:27017
    command:
      - mongod 
